src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/login', function () {
    return view('login');
});
Route::get('/login1', function () {
    return view('login1');
});

Route::get('/home', function () {
    return view('home');
});

Route::get('confirmexclude/{id}', 'AgendaController@confirmexclude');

Route::resource('pacientes', 'PacientesController');

Route::resource('novoorcamento', 'OrcamentoController');

Route::resource('agenda', 'AgendaController');


Route::get('/buscarorcamento', 'OrcamentoController@buscaorcamento');

Route::get('novoprontuario', 'OrcamentoController@novoprontuario');

Route::get('/forgot-password',function(){
    return view('forgot-password');
});


Route::resource('/perfil', 'PerfilController');
Route::post('/updateperfil', 'PerfilController@updateperfil');

Route::post('/teste1', 'ConsultorioController@teste');

Route::post('/export', 'ExportController@index');

Route::post('/exportprontuario', 'ExportController@exportprontuario');

Route::post('/solicitadados', 'OrcamentoController@solicitadados');

Route::get('/informardados', 'OrcamentoController@informardados');

Route::post('/incluiorcamento', 'OrcamentoController@inclueorcamento');

Route::resource('selecionarconsultorio', 'ConsultorioController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/savedata', 'AnamneseController@requestdata');

Route::get('deleteagendamento/{idagendamento}', 'AgendaController@destroy');

src/resources/views/agenda.blade.php
@extends('template')

@section('title', 'Agendar consulta')
@section('content')
<div class="container-fluid">

          <!-- Content Row -->
          <div class="row">

                <div class="col-lg-3">

	              <!-- Overflow Hidden -->
	              <div class="card mb-4">
	                <div class="card-header py-3">
	                  <h6 class="m-0 font-weight-bold text-primary corprontuario">Adicionar agendamento</h6>
	                </div>
	                <div class="card-body">
						{!! Form::open(['route' => 'agenda.store', 'method' => 'POST']) !!}

						<input type="hidden" name="user_id"value="{{$user_id}}">

						  <div class="form-group">
						    <label for="nome">Título</label>
						    <input type="text" id="nome" name="titulo" class="form-control" aria-describedby="emailHelp">
						    <small id="emailHelp" class="form-text text-muted">Informe o título do seu agendamento</small>
						  </div>
						  <div class="form-group">
						    <label for="Paciente">Paciente</label>
							<select  class="selectpicker" name="paciente_id">
							<option value=""></option> 
								@foreach ($paciente as $pacientes)
								<option value="{{$pacientes->id}}">{{$pacientes->nome}}</option> 
								@endforeach
							  </select>
						  </div>
						  <div class="form-group">
						    <label for="Clinica">Clinica</label>
							<select class="selectpicker" name="clinica_id">
							<option value=""></option> 
								@foreach ($clinicas as $clinica)
								<option value="{{$clinica->id}}">{{$clinica->nome}}</option> 
								@endforeach 
							  </select>
						  </div>
						  
						  <div class="form-group">
						    <label for="data">Data</label>
						    <input type="date" id="data" name="data" class="form-control">
						  </div>
						  
						  <div class="form-group">
						    <label for="hora">Hora</label>
						    <input type="time" id="hora" name="horario" class="form-control">
						  </div>
						  
						  <button type="submit" class="btn btn-primary">Salvar agendamento</button>
						  
						  {!! Form::close()!!}
	                </div>
	              </div>

	            </div>


                <div class="col-lg-9">

	              <!-- Overflow Hidden -->
	              <div class="card mb-4">
	                <div class="card-header py-3">
	                  <h6 class="m-0 font-weight-bold text-primary corprontuario">Calendário</h6>
	                </div>
	                <div class="card-body">
	                  <div id='calendar'></div>
	                </div>
	              </div>

	            </div>


				 <!-- @foreach ($agendamento as $agendamentos)
				<input type="hidden" name="" value="{{$busca_id_clinica =  $agendamentos->clinica_id}}">
				<input type="hidden" name="" value="{{$busca_clinica = App\Clinica::find($busca_id_clinica)}}">
				
				@endforeach -->
          </div>

        </div>
@endsection


<script>

		var agendamentos = [
		@foreach ($agendamento as $agendamentos)
		{
		    title: '{{$agendamentos->titulo}} \n @if($agendamentos->clinica_id == null)@else{{$busca_clinica = App\Clinica::find($agendamentos->clinica_id)->nome}}@endif ',
		    start: '{{$agendamentos->data}}T{{$agendamentos->horario}}',
		    backgroundColor: '#4b678e',
		    textColor: '#ffffff',
			url:'confirmexclude/{{$agendamentos -> id}}'
		},
		@endforeach
		];

      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
          plugins: [ 'dayGrid' ],
          locale: 'pt-br',
          events: agendamentos
        });

        calendar.render();
      });

</script>

src/resources/views/buscarorcamento.blade.php
@extends('template')

@section('title', 'Buscar orçamento')
@section('content')
<div class="container-fluid">

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary corbusca">Buscar Orçamentos</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>CPF</th>
                      <th>Data de Lançamento</th>
                      <th>Orçamento</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Nome</th>
                      <th>CPF</th>
                      <th>Data de Lançamento</th>
                      <th>Orçamento</th>
                    </tr>
                  </tfoot>
                  <tbody>
                  @foreach($orcamento as $orcamentos)
                  <tr>
                      <td>{{$orcamentos->nome}}</td>
                      <td>{{$orcamentos->cpf}}</td>
                      <td>{{date('d/m/Y "H:i:s"', strtotime($orcamentos->created_at))}}</td>
                      <td>
                        <a href="#" class="btn btn-primary btn-icon-split">
                          <span class="icon text-white-50">
                            <i class="fas fa-file-pdf"></i>
                          </span>
                          <form method="POST" action="{{ URL::to('/export') }}">
                          @csrf
                          <input type="hidden" value="{{$orcamentos->id}}" name="id">
                          <button type="submit" class="text">Abrir</button>
                          </form>
                        </a>
                      </td>
                    </tr>
                  @endforeach

                
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
@endsection

src/resources/views/confirmexclude.blade.php
<script>
var txt;
var r = confirm("Se deseja excluir, pressione o botão OK");
if (r == true) {
    window.location.href = 'http://192.168.4.18/deleteagendamento/{{$id}}';
} else {
    window.location.href = 'http://192.168.4.18/agenda';
}
</script>

src/resources/views/dadosorcamento.blade.php
@extends ('template')
@section('title', 'Selecionar Consultório')
@section('content')

<div class="container-fluid">

	<!-- Content Row -->
	<div class="row d-flex justify-content-center">

        <div class="col-md-10 col-xl-6">

			<div class="card mb-12">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary corprontuario">Informe os dados do paciente</h6>
				</div>
				<div class="card-body">

					<form  style="width: 100%;border:none;outline:none ;background-color:#fff;" method="POST" action="{{ URL::to('/solicitadados') }}">
						@csrf
						<div class="form-group">
							<label for="name">Nome*</label>
							<input type="text" class="form-control" name="nome" placeholder="Digite o nome" required>
						</div>
						<div class="form-group">
							<label for="cpf">CPF*</label>
							<input type="text" class="form-control" name="cpf" placeholder="Digite o CPF" data-mask="000.000.000-00" required>
						</div>

						<div style="float: right; bottom: 0; position: relative; margin-bottom: 15px">
							<button type="submit" class="btn btn-primary" value="Input" >Próximo</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

src/resources/views/forgot-password.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Esqueceu a senha</title>

	<!-- Custom fonts for this template-->
	<link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

	<!-- Custom styles for this template-->
	<link href="css/sb-admin-2.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

	<div class="container">

		<!-- Outer Row -->
		<div class="row justify-content-center">

			<div class="col-xl-10 col-lg-12 col-md-9">

				<div class="card o-hidden border-0 shadow-lg my-5">
					<div class="card-body p-0">
						<!-- Nested Row within Card Body -->

						<div class="row">
							<div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
							<div class="col-lg-6">     
								<div class="p-5">
									<div class="text-center">
										<h1 class="h4 text-gray-900 mb-2">Esqueceu sua senha?</h1>
										<p class="mb-4">Digite seu endereço de e-mail abaixo e enviaremos um link para redefinir sua senha!</p>
									</div>
									<form method="POST" class="user" action="">
										<div class="form-group">
											<input type="email" class="form-control form-control-user" id="InputEmail" aria-describedby="emailHelp" placeholder="Digite seu endereço de email">
										</div>
										<a href="login" class="btn btn-primary btn-user btn-block">
											Resetar senha
										</a>
									</form>
									<hr>
									<div class="text-center">
										<a class="small" href="register">Criar uma conta!</a>
									</div>
									<div class="text-center">
										<a class="small" href="login">Já tem uma conta? Faça login!</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>

		</div>

	</div>

	<!-- Bootstrap core JavaScript-->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Core plugin JavaScript-->
	<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

	<!-- Custom scripts for all pages-->
	<script src="js/sb-admin-2.js"></script>

</body>

</html>

src/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/resources/views/imprimeorcamento.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Orçamento</title>

    <style type="text/css">
        body {
    background-color: #000
}

.padding {
    padding: 2rem !important
}

.card {
    margin-bottom: 30px;
    border: none;
    -webkit-box-shadow: 0px 1px 2px 1px rgba(154, 154, 204, 0.22);
    -moz-box-shadow: 0px 1px 2px 1px rgba(154, 154, 204, 0.22);
    box-shadow: 0px 1px 2px 1px rgba(154, 154, 204, 0.22)
}

.card-header {
    background-color: #fff;
    border-bottom: 1px solid #e6e6f2
}

h3 {
    font-size: 20px
}

h5 {
    font-size: 15px;
    line-height: 26px;
    color: #3d405c;
    margin: 0px 0px 15px 0px;
    font-family: 'Circular Std Medium'
}

.text-dark {
    color: #3d405c !important
}

.imagens {
    border-top: 1px solid #e6e6f2;
}

.assinatura{
    margin-bottom: 80px;
    margin-top: 50px;
}
    </style>
  </head>
  <body>



 <div class="offset-xl-2 col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12 padding">
     <div class="card">
         <div class="card-header p-4">

           <h3 class="mb-0 float-left" >Dr.
           {{$users->name}}
           </h3> 

             <div class="float-right">
                 <h3 class="mb-0">CRODF {{$users->cro}}</h3>
                 
             </div>
         </div>
         <div class="card-body">
             <div class="row mb-4">
                 <div class="col-sm-6">
                    
                     <h3 class="text-dark mb-1">{{$clinica->nome}}</h3>
                     <div>{{$clinica->endereco}}</div>
                     <div>{{$clinica->cnpj}}</div>
                     <div>Telefone: {{$clinica->telefone}}</div>
                 </div>
                  <div class="col-sm-6">
                    
                     <h3 class="text-dark mb-1">Dados do Paciente</h3>
                     <div>Nome: {{$cliente->nome}}</div>
                     <div>CPF: {{$cliente->cpf}}</div>
                 </div>
             </div>
             <div class="imagens"><img src="img/dentesprontuario.fw.png" style="width: 100%;"></div>
             <div class="table-responsive-sm">
                 <table class="table table-striped" >
                     <thead>
                         <tr>
                             <th class="center">#</th>
                             <th>Região</th>
                             <th>Especialidade</th>
                             <th>Procedimento</th>
                         </tr>
                     </thead>
                     <tbody>
                     <input type="hidden" value="{{$count = 1 }}">
                    @foreach($dente_orcamento as $dentes)
                    <input type="hidden" value="{{$procedimento_name = App\Procedimento::where('id',$dentes->procedimento_id)->value('nome')}}">
                    <input type="hidden" value="{{$dente = App\Dente::where('id',$dentes->dente_id)->value('valor')}}">
                    <input type="hidden" value="{{$procedimento = App\Procedimento::where('id',$dentes->procedimento_id)->value('especialidade_id')}}">
                    <input type="hidden" value="{{$especialidade = App\Especialidade::where('id',$procedimento)->value('nome')}}">
                         <tr>
                             <td class="center">{{$count++}}</td>
                             <td class="left strong">{{ $dente }}</td>
                             <td class="left">{{$especialidade}}</td>
                             <td class="left">{{ $procedimento_name }}</td>
                         </tr>

                    @endforeach
                     </tbody>
                 </table>
             </div>
             <div class="row">
                 <div class="col-lg-4 col-sm-5">
                 </div>
                 <div class="col-lg-4 col-sm-5 ml-auto">
                     <table class="table table-clear">
                         <tbody>
                             <tr>
                                 <td class="left">
                                     <strong class="text-dark">Total</strong> </td>
                                 <td class="right">
                                    <input type="hidden" value="{{$preco = App\Orcamento::find($orcamento)}}">
                                     <strong class="text-dark">R${{$preco->preco}}</strong>
                                 </td>
                             </tr>
                         </tbody>
                     </table>
                 </div>
             </div>
         </div>
         <div class="row assinatura">
             <div class="col-md-6 text-center">
                 ________________________________________<br>Assinatura do Paciente
             </div>
             <div class="col-md-6 text-center">
                 ________________________________________<br>Assinatura do Dentista
             </div>
         </div>
         <div class="card-footer bg-white">
             <p class="mb-0 float-left">Connecteeth</p>
             <p class="mb-0 float-right">23 de Julho de 2020</p>
         </div>
     </div>
 </div>


 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

src/resources/views/novoorcamento.blade.php
@extends('template')

@section('title', 'Criar orçamento')
@section('content')
<div class="container-fluid">

    <!-- Linha -->
    <div class="row">

        <div class="col-lg-12">

            <!-- Odontograma -->
            {!! Form::open(['route' => 'novoorcamento.store', 'method' => 'POST']) !!}
            <div class="card mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary corprontuario">Odontograma</h6>
                </div>
                <div class="card-body" style="text-align: center;">
                    <table style="margin-left: auto; margin-right: auto;">
                        <tbody>

                            <tr>

                                @foreach ($dente1 as $dentes1)
                                <td class="colunadente">
                                    {{$dentes1->valor2}}
                                    <br> {{$dentes1->valor}}
                                    <br>
                                    <input class="{{$dentes1->nome}}" id="{{$dentes1->nome}}" type="checkbox" name="dente_id[]" onclick="denteSelecionado(this);" value="{{$dentes1->id}}"/>
                                    <label for="{{$dentes1->nome}}"></label>
                                </td>
                                @endforeach

                            <tr>
                                @foreach ($dente2 as $dentes2)
                                <td class="colunadente">
                                    <input class="{{$dentes2->nome}}" id="{{$dentes2->nome}}" type="checkbox" name="dente_id[]" onclick="denteSelecionado(this);" value="{{$dentes2->id}}"/>
                                    <label for="{{$dentes2->nome}}"></label>
                                    <br> {{$dentes2->valor}}
                                    <br> {{$dentes2->valor2}}
                                </td>
                                @endforeach
                            </tr>

                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

    <!-- Linha -->
    <div class="row">

        <div class="col-lg-3">

            <!-- Odontograma -->
            <div class="card mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary corprontuario">Especialidade</h6>
                </div>
                <div class="card-body">
                    <div class="list-group" id="myList" role="tablist">
                        <input type="hidden" value="{{$count = 0}}">
                        @foreach ($especialidade as $especialidades)
                        <input type="hidden" value="{{$count++}}">
                        <a class="list-group-item list-group-item-action @if ($count == 1) active @endif" data-toggle="list" href="#{{$especialidades->nome}}" role="tab">{{$especialidades->nome}}</a>
                        @endforeach
                  </div>
              </div>
          </div>

        </div>

        <div class="col-lg-3">

            <!-- Odontograma -->
            <div class="card mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary corprontuario">Procedimento</h6>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <input type="hidden" value="{{$count = 0}}">
                    @foreach ($especialidade as $especialidades)
                        <input type="hidden" value="{{$count++}}">
                    <div class="tab-pane @if ($count == 1) active @endif" id="{{$especialidades->nome}}" role="tabpanel">
                        <div class="list-group" id="myProcedimentoList" role="tablist">
                            <input type="hidden" name="" value="{{$buscaprocedimento = App\procedimento::where('especialidade_id',$especialidades->id)->get()}}">
                            @foreach ($buscaprocedimento as $procedimentos)


                            <div class="custom-control custom-radio">
                              <input type="radio" id="{{$procedimentos->id}}" name="procedimento_id" class="custom-control-input" href="#{{$procedimentos->nome_id}}" value="{{$procedimentos->id}}">
                              <label class="custom-control-label" for="{{$procedimentos->id}}">{{$procedimentos->nome}}</label>
                            </div>

                            @endforeach

                        </div>

                </div>
                @endforeach
                    </div>
              </div>
          </div>

        </div>

        <div class="col-lg-6">

            <!-- Odontograma -->
            <div class="card mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary corprontuario">Orçamento</h6>
                </div>
                <div class="card-body">
                      <div class="form-group">
                        <input type="hidden" value="{{$count = 0}}">
                        <div class="tab-content">
                                @foreach ($procedimento as $procedimentos)
                                <input type="hidden" value="{{$count++}}">
                                <div class="tab-pane @if ($count == 1) active @endif" id="{{$procedimentos->nome_id}}" name="{{$procedimentos->nome_id}}" role="tabpanel "><label>{{$procedimentos->nome}}</label></div> 
                                @endforeach
                        </div>

                        <input type="text" class="form-control" id="valor" name="valor" aria-describedby="region" placeholder="Valor do procedimento">
                        <small id="region" class="form-text text-muted"></small>
                    </div>
                    <button type="submit" class="btn btn-primary">Adicionar procedimento</button>
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="text-align:center">
                    <!-- <table style="text-align: center;"> -->
                    <tr>
                    <th>Procedimento</th>
                    <th>Dentes</th>
                    </tr>
                    @foreach($dente_orcamento as $dentes_orcamento)
                    <input type="hidden" value="{{$procedimento_name = App\Procedimento::where('id',$dentes_orcamento->procedimento_id)->value('nome')}}">
                    <input type="hidden" value="{{$dente = App\Dente::where('id',$dentes_orcamento->dente_id)->value('valor')}}">
                        <tr>
                        <td>{{$procedimento_name}}</td>
                        <td>{{$dente}}</td>
                        </tr>
                    @endforeach
                    </table>
                    <input type="hidden" value="{{$preco = App\Orcamento::find($orcamento)}}">
                    <br><br><hr class="sidebar-divider my-0"><br> Total  R$ {{$preco->preco}}

                    {!! Form::close()!!}

            </div>
        </div>

        </div>

    </div>

    <div class="row">

        <div class="col-lg-12">

            <!-- Odontograma -->
            <div class="card mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary corprontuario">Paciente</h6>
                </div>
                <div class="card-body">
                    <form style="display: inline"  method="POST" action="{{ URL::to('/incluiorcamento') }}">
                        @csrf
                      <div class="form-group">
                            <select class="selectpicker" name="paciente" data-show-subtext="true" data-live-search="true">
                                <option disabled selected>Buscar Prontuário</option>
                                @foreach ($paciente as $pacientes)
                                <option data-subtext="{{$pacientes->cpf}}" value="{{$pacientes->id}}">{{$pacientes->nome}}</option>
                                @endforeach 
                            </select>
                        <br>
                        <small id="emailHelp" class="form-text text-muted">Selecione um paciente existente e clique em "Incluir a prontuário", ou clique em "Novo prontuário" para realizar um novo cadastro.</small>
                      </div>
                      
                      <a href="{{URL::to('/buscarorcamento')}}"><span type="#"class="btn btn-primary" >Salvar</span></a>
                      <button type="submit" class="btn btn-info">Incluir a prontuário</button>
                    </form>
                      <a href="/novoprontuario" class="btn btn-warning">Novo prontuário</a>
                      <span class="btn btn-secondary btn-icon-split">
                        <span class="icon text-white-50">
                          <i class="fas fa-print"></i>
                        </span>
                        <form style="display: inline" method="POST" action="{{ URL::to('/export') }}">
                            @csrf
                            <input type="hidden" value="{{$orcamento}}" name="id">
                            <button class="btn btn-text-white-50" style="color: white">Imprimir</button>
                            </form>
                        
                        </span>
                </div>
            </div>

        </div>

    </div>

</div>
<!-- 
<script type="text/javascript">

    var dentesSelecionados = [];

    function denteSelecionado(checkboxDente) {
        if (dentesSelecionados.includes(checkboxDente.id)){
            dentesSelecionados.splice(dentesSelecionados.indexOf(checkboxDente.id), 1);
        } else {
            dentesSelecionados.push(checkboxDente.id);
        }


        var region = 'Região: ' + dentesSelecionados.join();
        var smallregion = document.getElementById('region');
        smallregion.innerHTML = region;
    }
</script> -->

@endsection

src/resources/views/selecionarconsultorio.blade.php
@extends('template')

@section('title', 'Selecionar Consultório')
@section('content')


<input type="hidden" value="{{$clinica = $user_id -> buscarClinica}}">

@if($clinica_id == null)
@if ($message = Session::get('success'))
<div class="alert alert-danger" role="alert" style=" width:300px; position:relative; margin: 0 auto; text-align:center "> 
  <p>{{ $message }}</p>
</div>
@else
<div class="alert alert-primary" role="alert" style=" width:300px; position:relative; margin: 0 auto; text-align:center "> 
Nenhum Consultório Selecionado
</div>
@endif
                @else
                <div class="alert alert-success" role="alert" style=" width:300px; position:relative; margin: 0 auto; text-align:center ">
                Consultório Selecionado : {{$clinica_id->nome}}
                </div>
@endif


@foreach ($clinica as $clinicas)
<div class="container-type-small">

  <div class="teste-close">
  <form  method ="POST" action="{{route('selecionarconsultorio.destroy', $clinicas->id)}}">
  @csrf
  <input name="_method" type="hidden" value="DELETE">
  <button class="close" type="sumbit" onclick="return confirm('AVISO!!!\nAo excluir esse consultório, você não terá mais acesso ao mesmo.\nTem certeza que deseja prosseguir com a exclusão?')">
      <span aria-hidden="true">×</span>
    </button>
    </form>
  </div>
  
  <div class="logo-clinic">
    <img src="img/clinic.png" height="100%" width="100%">
  </div>
  
  <div class="name-clinic">
    <span style="color: black">{{$clinicas->nome}}</span><br>
    <span style="color: black">{{$clinicas->telefone}}</span>
  </div>
  <form  style="width: 100%; border:none; outline:none; background-color:#fff;" method="POST" action="{{ URL::to('/teste1') }}">
    @csrf
    <input type="hidden" value="{{$clinicas->id}}" name="id">
    <button type="submit" style="height:100%; width: 100%; border:none; outline:none; background-color:#fff;"></button>
  </form>
</div>
@endforeach


<a href="#" data-toggle="modal" data-target="#consultorioModal">
    <div class="container-type-small" style="margin-bottom: 0px;">
    <div class="more-plus"><i class="fas fa-plus-square"></i></div>
  </div>

</a>



@endsection